### ISSUE TITLE
Let people create their own contests

### ISSUE THREAD

**Issue by Overbryd** [codebrawl/codebrawl#1]
In order to be more attractive for different kinds of programmers, we should let them create their own contests.

Feature: Contests

Scenario: A user creates his own contest
He visits the new contest page and fills in a name, tagline, description. He selects a starting date and voting date. Then he hits a button submit contest and lands on the contest page.
Another visitor is now able to see the contest on the contest listing. He may also see the contests page when clicking the contest title.
Any logged in user may participate in the contest.

**Comment by jeffkreeftmeijer** [comment]
My initial idea what that I would curate them myself and do (bi-)weekly contests. That way, I could start giving out prizes (if I'm able to find sponsors for that) and make sure we have high quality contests. Of course, I need help with that, so some way to try to let users suggest contests would be awesome.

I'm interested in your idea though, but I think it would be better to separate that from the "main" contests by putting them in something we call the "open room", or something like that.

Also, something I thought about was to have some kind of head to head battle idea, where two or more programmers could submit their own contest and see who can write the best solution. With a voting period, of course.

I'm not sure if we should start implementing something like this right now, but this is definitely something to think about. Let's put this one on hold for now. :)

**Comment by Overbryd** [comment]
Wow I didn't thought of prizes, but that makes things even more
awesome. I like this idea.
Also the quality of the contests must be high. I totally agree with that.

Separating "Open Contests" with the (bi) weekly "Main" contests is a
good thing, and I would totally go for that in order to keep the
sponsored contest with prices idea on top.

But to push things a little bit, I'll name some reasons to start
implementing Open Contests early on.
First of all, I realized that that people like to "fight" over things
more if they can be credited for the idea.
Second, the whole thing makes a lot more fun if more people engage on the site.
It would also improve the value of the project a lot if there are more
visitors and action on the site. By value I mean things like
attention, engagement and recurring users.
Gaining this kind of attraction through various kinds of programmers
(not only the ones attracted by the "main contest") would be a great
thing for the site.

I would offer you this: In consideration of your ideas, I'd take care
about the "open contests" part of the site. We could distinguish
between the main contest and the open contest. Therefore enabling us
to work on independent parts of the site.

**Comment by jeffkreeftmeijer** [comment]
Ok, you've convinced me. It would be awesome if you could start working on the open contests part. I'll mainly focus on the main contests right now. :)

**Comment by Overbryd** [comment]
Allright, cool having your agreement over this. I have already started
;) But it will take me some more time to finish.
The cool thing is, that all your work is tested in a very elegant
manner. It allows for quick improvements and feels really good
overall.

Cheers, Lukas

**Comment by jeffkreeftmeijer** [comment]
Awesome, pleas let me know if I need to help out with anything an please keep pushing everything you finish, I'd like to see how things are going! :)
