### ISSUE TITLE
Create a Contest Rules section

### ISSUE THREAD

**Issue by robertodecurnex** [codebrawl/codebrawl#19]
Right now the contest rules are just displayed when submitting the entry. 

Once a Gist ID is supplied this page is accessible no more.

Current contest rules pages:
http://codebrawl.com/contests/contest_slug_here/entries/new

Note that is only accessible if you are logged in and you don't have submitted a gist id yet (it also works with closed contests).

**Comment by jeffkreeftmeijer** [comment]
We should probably move the rules to a separate (static?) page and embed it into the new entry page in some way or another. Does anyone want to pick this up? @robertodecurnex even, maybe? :)

**Comment by robertodecurnex** [comment]
Yup, sure. Where should we put it ? 

http://codebrawl.com/rules

or

http://codebrawl.com/contests/rules

The first one looks better. Thoughts?

**Comment by jeffkreeftmeijer** [comment]
The first one sounds good. :)

**Comment by robertodecurnex** [comment]
![Codebrawl Rules Page](https://img.skitch.com/20110810-r34adpi9mgg62wpef43eckx4gh.png)

**Comment by robertodecurnex** [comment]
@jeffkreeftmeijer Let me know if you want to change anything at all.

**Comment by robertodecurnex** [comment]
Rules page under `/rules` now
