### ISSUE TITLE
Public profiles for every participant

### ISSUE THREAD

**Issue by Overbryd** [codebrawl/codebrawl#2]
**Note: I'm writing this down, because I could see that a user profile link is not implement everywhere**

In order to show others in what contests a user has participated and maybe even won, everybody can view the users profile.

Feature: Users

Scenario: View a users profile by clicking on a gravatar

Scenario: View a users profile by clicking on a name

**Comment by jeffkreeftmeijer** [comment]
I started working on the profile pages, but I removed the link to it (if you're logged in, you could click your name) to focus on other stuff before going live. There's a failing spec for the profile link.

Do you want to pick this up? :)

**Comment by Overbryd** [comment]
I'm on it.
