### ISSUE TITLE
Trouble traveling time with Travis and Timecop

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [codebrawl/codebrawl#20]
Somehow Timecop doesn't seem to be able to time travel properly on Travis. Here's [one of the builds that's failing](http://travis-ci.org/#!/codebrawl/codebrawl/builds/73798), but I can't seem to reproduce what's going wrong. If anyone has an idea, please let me know. :)

**Comment by robertodecurnex** [comment]
@jeffkreeftmeijer talking about the business logic, looking at the model looks like contests should be starting at 14:00:00 UTC but the tests are expecting 12:00:00 UTC :S

The site states 14:00:00 UTC too.

It's working for you cuz you are in a +2 timezone, wrong by 5 hours here cuz I'm a -3 guy. 

It's definitely using the system tiemezone at some point (already fiexed on my side ;)). Just tell me if we should aim to open/close periods at 12:00:00 UTC ot 14:00:00 UTC
