### ISSUE TITLE
How do you add an entry?

### ISSUE THREAD

**Issue by technoweenie** [codebrawl/codebrawl#25]
I've been trying to add my entry to the latest codebrawl for days, but the app is busted.  I've tried public and private gist IDs and URLs.

**Comment by jeffkreeftmeijer** [comment]
Hey Rick,

What's the error message you've been getting? Could you Github-message me your Gist ID so I can take a look and make sure your entry gets in before the contest closes? :)

Sorry about this!
- Jeff

**Comment by technoweenie** [comment]
Thanks.  I sent you a DM.
