### ISSUE TITLE
List users contest on their profile page

### ISSUE THREAD

**Issue by Overbryd** [codebrawl/codebrawl#3]
In order to keep track of contests created by a user, the user wants to see a list of his own contests on his profile page.

Feature: Contests

Scenario: List contests created by myself on my profile page
A user is logged in and has created a contest "Optimizing Ruby Performance".
When he visits his profile page, he can see "Optimizing Ruby Performance" in the contests list.

**Comment by jeffkreeftmeijer** [comment]
There's a contest list on the hidden profile pages already. It could use some work, though. :)

**Comment by Overbryd** [comment]
I'm on it.
