### ISSUE TITLE
ruby 1.9 and 1.8.7 support

### ISSUE THREAD

**Issue by ghost** [codebrawl/codebrawl#5]

**Comment by ghost** [comment]
1.8.6 is just too old...

**Comment by jeffkreeftmeijer** [comment]
I'm not sure what you mean here, but Codebrawl is running on 1.9.2 right now and I haven't tested it on 1.8 since the production box runs 1.9.2. Could you explain yourself a bit more? :)

**Comment by ghost** [comment]
I meant the ruby interpreter for the solutions.

**Comment by ghost** [comment]
forget it, I mixed up codebrawl with codeeval..

**Comment by jeffkreeftmeijer** [comment]
There's no Ruby interpreter for the solutions, the contests are completely open ended and we show the submissions' code in the voting period to let other users vote which entries they like best and which implementation is the cleanest. :)
