### ISSUE TITLE
Distribute New Brawls via RSS

### ISSUE THREAD

**Issue by geoffreywiseman** [codebrawl/codebrawl#6]
People interested in participating in new code brawls might want to know when new brawls launch without having to visit the website.  There are lots of ways this could happen (email, twitter), but my choice would definitely be RSS.

**Comment by jeffkreeftmeijer** [comment]
I'll accept patches for this as it will take me a while to get to it. Any takers? @geoffreywiseman maybe even you? :)

Also, I love the idea of calling the contests "brawls" instead. :)

**Comment by jeffkreeftmeijer** [comment]
http://feeds.feedburner.com/codebrawl :)

**Comment by geoffreywiseman** [comment]
Wow -- your definition of "take me a while to get to" is different than mine. I'm definitely not going to get to doing this. ;)

**Comment by inkel** [comment]
The definition of _take me a while to get to_ changed a lot thanks to Google ;)

**Comment by jeffkreeftmeijer** [comment]
Yes, credit should go to @inkel. :)

 I reopened this one because the auto_discovery_link still needs to be put back, with the feedburner URL.

**Comment by inkel** [comment]
I'll take a look at it then.

**Comment by inkel** [comment]
Done! Fixed in @0a02056eef8dafb5e89d

**Comment by jeffkreeftmeijer** [comment]
Thanks @inkel, merged into develop. :)
