### ISSUE TITLE
Rating/ranking system UI confusing

### ISSUE THREAD

**Issue by jspillers** [codebrawl/codebrawl#8]
Currently the rating system's 1 through 5 approach using radio buttons might be confusing to some people. What is essentially an individual quality rating (1 being the worst and 5 being the best) might be misconstrued as a quality ordering system (ie: 1 being the best and 5 being the worst). 

A simple change of UI to using 5 stars or thumbs up icons might clear up this confusion without having to change the underlying system at all.

**Comment by jeffkreeftmeijer** [comment]
I'm working on a new voting system that will definitely include your ideas. I'll use this issue for that. :)

**Comment by jeffkreeftmeijer** [comment]
The new voting system is live, please create a new issue if you're having problems again. :)
